### ISSUE TITLE
Unknown capture type 1 when decoding specific Alan Wake 2 *.binlua files (1.0.8 alpha)

### ISSUE THREAD

**Issue by riverence** [atrexus/unluau#27]
When decoding .binlua files (quite literally luau renamed to binlua, thanks Remedy) simple scripts *will* work and output something right, but on a good chunk the decompiler will produce this error;

`[20:01:12 FTL] Decompilation error
Unluau.DecompilerException: Unknown capture type 1
   at Unluau.Lifter.LiftBlock(Function function, Registers registers, Int32 pcStart, Int32 pcStop) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Lifter.cs:line 528
   at Unluau.Lifter.LiftProgram() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Lifter.cs:line 36
   at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Decompiler.cs:line 48
   at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau.CLI\Program.cs:line 119`

Is this an issue regarding support of for loops?

**Comment by atrexus** [comment]
No, I don't this has anything to do with for loops at all. There seems to be an issue regarding capture types in closures, specifically `Reference` capture types. 

Would it be possible for you to send me the binary that you were trying to decompile? If you are unable to, the disassembly will be just fine.

Thanks for finding this bug, I must of overlooked it.

**Comment by riverence** [comment]
Sure, I'll include two files; one that works (weapon_balancing_data.binlua), and one that doesn't (flashlight.binlua).
[binlua.zip](https://github.com/atrexus/unluau/files/13896698/binlua.zip)

**Comment by riverence** [comment]
I also get another different error on different files; 
`[21:40:25 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\IfElse.cs:line 28
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Block.cs:line 33
   at Unluau.Closure.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Expressions\Closure.cs:line 47
   at Unluau.Assignment.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Assignment.cs:line 30
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.OuterBlock.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24
   at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Decompiler.cs:line 53
   at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau.CLI\Program.cs:line 119`
[playable_character_selector.zip](https://github.com/atrexus/unluau/files/13897058/playable_character_selector.zip)

**Comment by atrexus** [comment]
@riverence Thank you for all of the bugs, I will get to them as soon as possible.

**Comment by atrexus** [comment]
> Sure, I'll include two files; one that works (weapon_balancing_data.binlua), and one that doesn't (flashlight.binlua). [binlua.zip](https://github.com/atrexus/unluau/files/13896698/binlua.zip)

After doing some debugging I was able to fix this issue, but another one arose. I noticed that `flashlight.binlua` is trying to load a closure (function) with upvalues, but then doesn't capture any of them. 

I will continue to look into this issue, but I think the bytecode is flawed.

**Comment by riverence** [comment]
Not sure why that would be happening, only thing I can think of that has a slight chance of being the reason is the dependency on the currently-missing `bigfish.lua`. This has popped up as a requirement in most decompiled scripts I've seen from this game, but isn't actually present, atleast not as a separate script.

**Comment by atrexus** [comment]
> Not sure why that would be happening, only thing I can think of that has a slight chance of being the reason is the dependency on the currently-missing `bigfish.lua`. This has popped up as a requirement in most decompiled scripts I've seen from this game, but isn't actually present, atleast not as a separate script.

Ok. I was wrong originally. After debugging for a bit more I saw that the script is creating a new closure (`OP_NEWCLOSURE`) and then it captures only one upvalue. The target closure has a requirement of two upvalues. I am not sure if this is allowed in Luau bytecode, but if you got this from a Roblox game, then this is most likely something on my end. I will take a look at the VM to see if they handle situations like this. 

Thanks again for finding this, I had not accounted for this previously.

**Comment by riverence** [comment]
I actually didn't get this from a Roblox game; this is from Alan Wake 2. The game uses Luau for it's scripts (which is one of the first examples of a game other than Roblox using it). Thanks for looking into this!

**Comment by riverence** [comment]
> I also get another different error on different files; `[21:40:25 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues System.NullReferenceException: Object reference not set to an instance of an object. at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\IfElse.cs:line 28 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Block.cs:line 33 at Unluau.Closure.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Expressions\Closure.cs:line 47 at Unluau.Assignment.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Assignment.cs:line 30 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.OuterBlock.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24 at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Decompiler.cs:line 53 at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau.CLI\Program.cs:line 119` [playable_character_selector.zip](https://github.com/atrexus/unluau/files/13897058/playable_character_selector.zip)

Now that the capture issue has been fixed, while it has opened up my scope on the scripts I can actually decompile, I'm getting more variations on this specific error. They don't always produce the same traceback either, which makes me think it's gonna be horrible to actually look into on a consistent basis. On some occasions, it'll actually produce output in the specified file, but it always cuts off at strange locations, like in the middle of a function. I've attached a zip file containing a few files that don't work. 
[objectnotset.zip](https://github.com/atrexus/unluau/files/13927154/objectnotset.zip)

**Comment by atrexus** [comment]
> > I also get another different error on different files; `[21:40:25 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues System.NullReferenceException: Object reference not set to an instance of an object. at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\IfElse.cs:line 28 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Block.cs:line 33 at Unluau.Closure.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Expressions\Closure.cs:line 47 at Unluau.Assignment.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Assignment.cs:line 30 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.OuterBlock.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24 at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Decompiler.cs:line 53 at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau.CLI\Program.cs:line 119` [playable_character_selector.zip](https://github.com/atrexus/unluau/files/13897058/playable_character_selector.zip)
> 
> Now that the capture issue has been fixed, while it has opened up my scope on the scripts I can actually decompile, I'm getting more variations on this specific error. They don't always produce the same traceback either, which makes me think it's gonna be horrible to actually look into on a consistent basis. On some occasions, it'll actually produce output in the specified file, but it always cuts off at strange locations, like in the middle of a function. I've attached a zip file containing a few files that don't work. [objectnotset.zip](https://github.com/atrexus/unluau/files/13927154/objectnotset.zip)

Thank you. I will look into this a little more. When decompiling your other scripts the main issue was that some elements of the AST are null. This is connected with register manipulation. I will try to fix this.

**Comment by atrexus** [comment]
> > I also get another different error on different files; `[21:40:25 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues System.NullReferenceException: Object reference not set to an instance of an object. at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\IfElse.cs:line 28 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Block.cs:line 33 at Unluau.Closure.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Expressions\Closure.cs:line 47 at Unluau.Assignment.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Assignment.cs:line 30 at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\Statement.cs:line 20 at Unluau.OuterBlock.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24 at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau\Decompiler.cs:line 53 at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.8-alpha\src\Unluau.CLI\Program.cs:line 119` [playable_character_selector.zip](https://github.com/atrexus/unluau/files/13897058/playable_character_selector.zip)
> 
> Now that the capture issue has been fixed, while it has opened up my scope on the scripts I can actually decompile, I'm getting more variations on this specific error. They don't always produce the same traceback either, which makes me think it's gonna be horrible to actually look into on a consistent basis. On some occasions, it'll actually produce output in the specified file, but it always cuts off at strange locations, like in the middle of a function. I've attached a zip file containing a few files that don't work. [objectnotset.zip](https://github.com/atrexus/unluau/files/13927154/objectnotset.zip)

Take at look at the most recent version, I added a few more things.

**Comment by riverence** [comment]
> Take at look at the most recent version, I added a few more things.
Unfortunately, after building and testing 1.0.9,  I'm still getting the object error, specifically on white_light_zone_system.binlua in my previous attachment.
`[07:51:00 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unluau.NameIndex.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Expressions\NameIndex.cs:line 27
   at Unluau.LocalExpression.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Expressions\LocalExpression.cs:line 32
   at Unluau.FunctionCall.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Expressions\FunctionCall.cs:line 40
   at Unluau.LocalExpression.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Expressions\LocalExpression.cs:line 32
   at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\IfElse.cs:line 28
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Block.cs:line 33
   at Unluau.IfElse.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\IfElse.cs:line 31
   at Unluau.Statement.WriteSequence(Output output, IList 1 statements) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.Block.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Block.cs:line 33
   at Unluau.Closure.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Expressions\Closure.cs:line 47
   at Unluau.Assignment.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Assignment.cs:line 30
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.OuterBlock.Write(Output output) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24
   at Unluau.Decompiler.Decompile() in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau\Decompiler.cs:line 53
   at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\infur\Documents\unluau-1.0.9-alpha (2)\src\Unluau.CLI\Program.cs:line 1`

**Comment by strawbberrys** [comment]
I'm also getting the same error on another script when using Client encoding.  [code.luau.txt](https://github.com/atrexus/unluau/files/13941958/code.luau.txt)

``> ./src/Unluau.CLI/bin/Debug/net6.0/linux-x64/Unluau.CLI --encoding Client code.luau`` => ``Object reference not set to an instance of an object.``

**Comment by atrexus** [comment]
Just pushed a new change that should fix a few scripts. Not all.

**Comment by atrexus** [comment]
Just wanted to check in quickly. I have been rewriting Unluau for the past weeks and am adding an IL to facilitate control flow analysis. Hopefully this set up will resolve most issues the alpha version faces.

**Comment by riverence** [comment]
nice! hopefully this can help me get through all of the scripts from alan wake 2 c:
