### ISSUE TITLE
exception when trying to decompile roblox luaubytecode (v2)

### ISSUE THREAD

**Issue by ChloeDoesThings** [atrexus/unluau#44]
whenever i try to decompile bytecode generated from getscriptbytecode, i get an error like this

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than or equal to the size of the collection. (Parameter 'index')
   at Unluau.Chunk.Luau.VectorConstant..ctor(Single[] values) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\Luau\Constant.cs:line 155
   at Unluau.Chunk.Luau.Function.ReadConstants(BinaryReader reader) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\Luau\Function.cs:line 224
   at Unluau.Chunk.Luau.Function..ctor(BinaryReader reader, Version version, String[] symbolTable) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\Luau\Function.cs:line 117
   at Unluau.Chunk.LuauChunk.ReadFunctions(BinaryReader reader) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\LuauChunk.cs:line 96
   at Unluau.Chunk.LuauChunk..ctor(BinaryReader reader) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\LuauChunk.cs:line 58
   at Unluau.Chunk.LuauChunk.Create(Stream stream) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau\Chunk\LuauChunk.cs:line 20
   at Unluau.CLI.Program.Main(String[] args) in C:\Users\reids\Downloads\ChloeRT\unluau-2.0.0-beta\src\Unluau.CLI\Program.cs:line 11
```

Any way I can fix this? This is the v2 one btw.

**Comment by ChloeDoesThings** [comment]
[input.txt](https://github.com/atrexus/unluau/files/14822974/input.txt)
this is the bytecode if you need it

**Comment by atrexus** [comment]
I think there is a bug when reading vector constants (I will investigate). Also, please use v1 for now, its the most stable version, v2 is still under heavy development.

**Comment by ChloeDoesThings** [comment]
> I think there is a bug when reading vector constants (I will investigate). Also, please use v1 for now, its the most stable version, v2 is still under heavy development.

alright thank you

**Comment by w5b** [comment]
getting the same error
this is the bytecode:
[InfestationCyst.txt](https://github.com/atrexus/unluau/files/15039618/InfestationCyst.txt)
