### ISSUE TITLE
FTL ( Fatal Error )  NullReferenceException encountered

### ISSUE THREAD

**Issue by Dankri12** [atrexus/unluau#56]
**Description of the issue:**
When trying to decompile a module script with Unluau, I encounter a NullReferenceException error.

**Roblox script by bytecode**
[input.txt](https://github.com/atrexus/unluau/files/14969105/input.txt)

**Steps to Reproduce:**

1.  Run Unluau.CLI with the --encoding option on the module script. 
```
Unluau.CLI.exe  --encoding Client -o test\output.txt test\input.txt
```
2.  Observe the output.

**Behavior:**
The following warnings and fatal error occur:
```
[03:10:22 WRN] Encountered unhandled code SETUPVAL, skipping
[03:10:22 WRN] Encountered unhandled code FASTCALL2, skipping
[02:36:31 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues

at Unluau.Lifter.LiftBlock(Function function, Registers registers, Int32 pcStart, Int32 pcStop) in C:\Users\hacking\Downloads\unluau\src\Unluau\Lifter\Lifter.cs:line 554

at Unluau.Lifter.LiftBlock(Function function, Registers registers, Int32 pcStart, Int32 pcStop) in C:\Users\hacking\Downloads\unluau\src\Unluau\Lifter\Lifter.cs:line 570

at Unluau.Lifter.LiftProgram() in C:\Users\hacking\Downloads\unluau\src\Unluau\Lifter\Lifter.cs:line 38

at Unluau.Decompiler.Decompile() in C:\Users\hacking\Downloads\unluau\src\Unluau\Decompiler.cs:line 48

at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\hacking\Downloads\unluau\src\Unluau.CLI\Program.cs:line 119
```

**Environment:**

1. **OS:** 
windows 10

2. **Unluau version:** 
Unluau 1.0.9-alpha

3. **.NET version:** 
8.0.203

**Comment by ChloeDoesThings** [comment]
It seems to be an issue with the lifter, I'll try to help you fix this in the morning since it's like 2:48.

**Comment by Dankri12** [comment]
> It seems to be an issue with the lifter, I'll try to help you fix this in the morning since it's like 2:48.

Sorry didnt see the message until now, Thats great to hear!

ive experienced  that im getting the same issue on a lot of other scripts aswell. during a lot of testing it seems i get the error from large or medium scripts. small scripts aint a problem. or i havent discovered any yet

**Comment by ChloeDoesThings** [comment]
> > It seems to be an issue with the lifter, I'll try to help you fix this in the morning since it's like 2:48.
> 
> Sorry didnt see the message until now, Thats great to hear!
> 
> ive experienced that im getting the same issue on a lot of other scripts aswell. during a lot of testing it seems i get the error from large or medium scripts. small scripts aint a problem. or i havent discovered any yet

I'm so sorry I completely forgot to see what the actual issue was.

**Comment by Dankri12** [comment]
> > > It seems to be an issue with the lifter, I'll try to help you fix this in the morning since it's like 2:48.
> > 
> > 
> > Sorry didnt see the message until now, Thats great to hear!
> > ive experienced that im getting the same issue on a lot of other scripts aswell. during a lot of testing it seems i get the error from large or medium scripts. small scripts aint a problem. or i havent discovered any yet
> 
> I'm so sorry I completely forgot to see what the actual issue was.

No worries, There is no rush.  Looking forward to your insights!
