### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MyoldhamiYeari** [atrexus/unluau#60]
Stacktrace

```
Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unluau.NameIndex.Write(Output output) in D:\unluau\src\Unluau\Lifter\Expressions\NameIndex.cs:line 27
   at Unluau.Assignment.Write(Output output) in D:\unluau\src\Unluau\Lifter\Statements\Assignment.cs:line 37
   at Unluau.ForLoopNumeric.Write(Output output) in D:\unluau\src\Unluau\Lifter\Statements\ForLoopNumeric.cs:line 30
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in D:\unluau\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.Block.Write(Output output) in D:\unluau\src\Unluau\Lifter\Statements\Block.cs:line 33
   at Unluau.Closure.Write(Output output) in D:\unluau\src\Unluau\Lifter\Expressions\Closure.cs:line 45
   at Unluau.Assignment.Write(Output output) in D:\unluau\src\Unluau\Lifter\Statements\Assignment.cs:line 30
   at Unluau.Statement.WriteSequence(Output output, IList`1 statements) in D:\unluau\src\Unluau\Lifter\Statements\Statement.cs:line 20
   at Unluau.OuterBlock.Write(Output output) in D:\unluau\src\Unluau\Lifter\Statements\OuterBlock.cs:line 24
   at Unluau.Decompiler.Decompile() in D:\unluau\src\Unluau\Decompiler.cs:line 51
   at Unluau.CLI.Program.RunOptions(Options options) in D:\unluau\src\Unluau.CLI\Program.cs:line 119
```

If required, the lua u bytecode will be attached in this message.
[theluauTXT.txt](https://github.com/user-attachments/files/16020611/theluauTXT.txt)

**Comment by MyoldhamiYeari** [comment]
Launched with --encoding "Client"
