### ISSUE TITLE
(v6 problem)

### ISSUE THREAD

**Issue by DJYazan** [atrexus/unluau#63]
Hello! i have *tried* to update unluau v1 to v6. Unfortunately i am coming across an issue. This: [19:45:43 DBG] Reading 16 strings from the string table
[19:45:43 DBG] Reading 16 strings from the string table
[19:45:43 DBG] Reading 0 functions from main bytecode pool
[19:45:43 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Unluau.Lifter.LiftProgram() in C:\Users\i like money\Downloads\Compressed\unluau-main_2\unluau-main\src\Unluau\Lifter\Lifter.cs:line 35
   at Unluau.Decompiler.Decompile() in C:\Users\i like money\Downloads\Compressed\unluau-main_2\unluau-main\src\Unluau\Decompiler.cs:line 48
   at Unluau.CLI.Program.RunOptions(Options options) in C:\Users\i like money\Downloads\Compressed\unluau-main_2\unluau-main\src\Unluau.CLI\Program.cs:line 119
   
   Can anyone Help? i will try to get the bytecode again!

**Comment by DJYazan** [comment]
![image](https://github.com/user-attachments/assets/6dd3bfc4-c7f7-49ea-96b5-7549457f3161)
this is l35in my unluau src

**Comment by DJYazan** [comment]
Also it went through the Type check i put (it would error if it didnt e.x) ```
[19:44:49 FTL] Decompilation error
Unluau.DecompilerException: Bytecode Types Version Mismatch! expected (1 .. 3, got 3)!
```
