### ISSUE TITLE
ReadBoolean encountered non-boolean value

### ISSUE THREAD

**Issue by scfmod** [atrexus/unluau#65]
I'm having some issues decompiling a bytecode file, if anyone could have a look into why this happens :-)

```
[11:08:43 DBG] Reading 22 strings from the string table
[11:08:43 DBG] Reading 4 functions from main bytecode pool
[11:08:43 DBG] Reading basic function prototype information
[11:08:43 DBG] Reading 2 instructions from function prototype body
[11:08:43 WRN] Encountered unexpected NOP instruction.
[11:08:43 DBG] Reading 0 constants from function prototype body
[11:08:43 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.IO.InvalidDataException: ReadBoolean encountered non-boolean value: 0x02
   at Unluau.BytecodeReader.ReadBoolean() in C:\tmp\unluau\src\Unluau\Deserializer\Reader\BytecodeReader.cs:line 61
   at Unluau.Deserializer.ReadLineInfo(Int32 instructions) in C:\tmp\unluau\src\Unluau\Deserializer\Deserializer.cs:line 252
   at Unluau.Deserializer.ReadFunction(IList`1 functions, IList`1 strings) in C:\tmp\unluau\src\Unluau\Deserializer\Deserializer.cs:line 138
   at Unluau.Deserializer.ReadFunctions(IList`1 strings) in C:\tmp\unluau\src\Unluau\Deserializer\Deserializer.cs:line 94
   at Unluau.Deserializer.Deserialize() in C:\tmp\unluau\src\Unluau\Deserializer\Deserializer.cs:line 42
   at Unluau.Decompiler..ctor(Stream stream, DecompilerOptions options) in C:\tmp\unluau\src\Unluau\Decompiler.cs:line 39
   at Unluau.CLI.Program.RunOptions(Options options) in C:\tmp\unluau\src\Unluau.CLI\Program.cs:line 114
```

Example file:
[bytecode_file.zip](https://github.com/user-attachments/files/17714796/bytecode_file.zip)

**Comment by Shad0wlife** [comment]
I see we are trying to do the same thing and are running into the same issue :D . Honestly, I think there might already be an issue with the proper string decoding. Sadly this is not as advanced as LuaJIT was.

**Comment by scfmod** [comment]
A bit of progress, if you remove the first byte in this file it works :-)

However some files produce errors, e.g from file attached:
```
...
[10:32:20 DBG] Reading 64 constants from function prototype body
[10:32:20 DBG] Line information is enabled, reading.
[10:32:20 DBG] Debug information is enabled, reading.
[10:32:20 WRN] Encountered unhandled code FASTCALL1, skipping
[10:32:20 WRN] Encountered unhandled code FASTCALL2, skipping
[10:32:20 WRN] Encountered unhandled code FASTCALL1, skipping
[10:32:20 FTL] Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unluau.NameIndex.GetNames() in C:\tmp\unluau\src\Unluau\Lifter\Expressions\NameIndex.cs:line 33
   at Unluau.LocalExpression.GetNames() in C:\tmp\unluau\src\Unluau\Lifter\Expressions\LocalExpression.cs:line 43
   at Unluau.NameIndex.GetNames() in C:\tmp\unluau\src\Unluau\Lifter\Expressions\NameIndex.cs:line 33
   at Unluau.FunctionCall.GetNames() in C:\tmp\unluau\src\Unluau\Lifter\Expressions\FunctionCall.cs:line 58
   at Unluau.Namer.getName(Expression expression) in C:\tmp\unluau\src\Unluau\Lifter\Namer.cs:line 82
   at Unluau.Namer.createNamedDecleration(Int32 register, Expression expression, Block block, DeclerationType type) in C:\tmp\unluau\src\Unluau\Lifter\Namer.cs:line 65
   at Unluau.Namer.CreateDecleration(Int32 register, Expression expression, Block block, DeclerationType type, Boolean isRegular) in C:\tmp\unluau\src\Unluau\Lifter\Namer.cs:line 34
   at Unluau.Registers.LoadTempRegister(Int32 register, Expression expression, Block block, DeclerationType type) in C:\tmp\unluau\src\Unluau\Lifter\Registers.cs:line 62
   at Unluau.Lifter.LiftBlock(Function function, Registers registers, Int32 pcStart, Int32 pcStop) in C:\tmp\unluau\src\Unluau\Lifter\Lifter.cs:line 203
   at Unluau.Lifter.LiftBlock(Function function, Registers registers, Int32 pcStart, Int32 pcStop) in C:\tmp\unluau\src\Unluau\Lifter\Lifter.cs:line 552
   at Unluau.Lifter.LiftProgram() in C:\tmp\unluau\src\Unluau\Lifter\Lifter.cs:line 38
   at Unluau.Decompiler.Decompile() in C:\tmp\unluau\src\Unluau\Decompiler.cs:line 48
   at Unluau.CLI.Program.RunOptions(Options options) in C:\tmp\unluau\src\Unluau.CLI\Program.cs:line 119
```

[bytecode_file_2.zip](https://github.com/user-attachments/files/17729983/bytecode_file_2.zip)

**Comment by Achimobil** [comment]
But you have seen that the first byte in the file will tell you the version of the luau, so remove is a little bit useless, or?

**Comment by scfmod** [comment]
The game .exe uses both first and second byte to deduce bytecode version, the decompiler does only need the 2nd byte

**Comment by scfmod** [comment]
As a side note, the v2.0.0-beta branch does successfully disassemble the files I've tested with so far without any errors :-)
Though it does not generate any Luau code (yet)

**Comment by Achimobil** [comment]
> The game .exe uses both first and second byte to deduce bytecode version, the decompiler does only need the 2nd byte

The decompiler in source code use definetly the first byte to make sure it is a min version 3.
This is checked in the first read operation ;)

**Comment by scfmod** [comment]
Yes, I'm not talking about the decompiler .exe but the .exe that actually uses these files :-)

**Comment by Achimobil** [comment]
I get it with the 2 to work with a small change, but I assume there is not create of readably lua code yet. Perhaps @atrexus could give the answer there, because I only can use it with disassemble option currently

**Comment by Shad0wlife** [comment]
When I check the docs both bytes should be there. V4 just has that additional byte for TypeVersion.

I think that the handling for the typeversion in the "old" compiler breaks some offset or something.
I'm gonna check the 2.0.0 beta as well, I think using an AST is how ljd did it as well, so maybe adding a decompiler onto the AST can learn from that.

**Comment by Shad0wlife** [comment]
> As a side note, the v2.0.0-beta branch does successfully disassemble the files I've tested with so far without any errors :-) Though it does not generate any Luau code (yet)

I had to disable the TypedVersion check on the 2.0.0 as well to get anything useful? I don't really understand why though.

**Comment by scfmod** [comment]
Okay, so these are error messages from the GAME .exe when modifying the 2 first bytes of unencoded bytecode:

```
0x02 0xEE = "bytecode version mismatch (expected [3..4], got 2)"
0x02 0xEF = 3
0x02 0xF0 = 4
0x02 0xF1 = "bytecode version mismatch (expected [3..4], got 5)"

0x01 0xEF = "bytecode version mismatch (expected [3..4], got 239)"
0x03 0xEF = "bytecode version mismatch (expected [3..4], got 245)"
```

**Comment by Shad0wlife** [comment]
Alright, I got the disassembly working now when skipping the user type evaluation and after adding proper handling for loops so the graph logic didn't die, but I can see where the loop loops.

Next I will try to make the graph load/show referenced values instead of the addresses. I think that's a sensible step towards generating a code output.

**Comment by 076c** [comment]
recompile it and see if it works. Tampering with the bytecode is not a great solution.
